// User-visible string constants — i18n reserve.
// One flat object, grouped by domain. Values are byte-identical copies of the
// strings previously inlined across src/lib and src/components; this file
// does not change any behavior or visible copy, only where it lives.
// See docs/feature-predesign-cleanup-prompt.md for the externalization plan.

export const S = {
  common: {
    confirmOperation: '确认操作',
    confirm: '确认',
    cancel: '取消',
    undo: '撤销',
  },
  review: {
    again: '重来',
    remember: '记住',
    flipHint: '轻点翻面 · TAP TO FLIP',
    hard: '困难',
    easy: '容易',
    later: '稍后', // used as a control-flow sentinel via === in Review.jsx's predictInterval(), not decorative-only text
    title: '复习',
    doneZh: '今日复习完成',
    reviewedCount: '已复习',
    correctRate: '正确率',
    undoLastCard: '撤销上一张',
    backToDeck: '返回卡组',
    browseCards: '浏览卡片',
    leechToast: '卡片已标记为顽固卡并暂停 · LEECH',
    ratedToastPrefix: '已評分 · ',
    undoToast: '已撤銷',
    undoToastLabel: '撤销',
    learningPrefix: '学习中 · ',
  },
  cardEditor: {
    edit: '编辑',
    preview: '预览',
    frontPlaceholder: '正面 · 问题',
    backPlaceholder: '背面 · 答案',
    save: '保存',
    add: '添加',
    cancel: '取消',
    tableTemplate: '| 列1 | 列2 |\n| --- | --- |\n| ',
  },
  error: {
    boundaryTitle: '出错了',
    reload: '重新加载',
  },
  structure: {
    empty: '暂无数据',
  },
  storage: {
    quotaFlashcard: '请导出备份后清理数据',
    genericUnsaved: '数据未保存',
    quotaFull: (detail) => `储存空间已满，${detail}`,
  },
  reviewLog: {
    unsaved: '复习日志未保存',
  },
  reviewSession: {
    unsaved: '复习会话未保存',
  },
  autoBackup: {
    statusUnsaved: '自动备份状态未保存',
  },
  reminders: {
    dueBody: (count) => `${count} 张卡片待复习`,
    wrongBookSuffix: (size) => ` · 错题 ${size}`,
    title: 'Mnemos · 今日复习',
    channelName: '复习提醒',
  },
  activity: {
    todayTitle: '今日 · TODAY',
    todayCompletionAria: (percentValue) => `今日完成度 ${percentValue}%`,
    recallRingLabel: '记忆 · ',
    practiceRingLabel: '练习 · ',
    readingRingLabel: '阅读 · ',
    dayLabelsShort: ['日', '一', '二', '三', '四', '五', '六'],
    monthNames: ['', '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    heatmapTitle: '热力 · HEATMAP',
    heatmapDays: '90 天',
    recallDetailPrefix: '记忆 ',
    practiceDetailPrefix: '练习 ',
    readingDetailPrefix: '阅读 ',
    back: '返回',
    pageTitle: '活动',
    thisMonth: '本月',
    monthLabel: 'MONTH · 本月',
    streakSuffix: ' 日连续',
    activeDaysLabel: '活跃天数',
    thisWeekLabel: '本周活动',
    totalLabel: '总活动量',
    calendarTitle: '月历 · CALENDAR',
    calendarDaysSuffix: ' 天',
    modulesTitle: '模块 · MODULES',
    readonlyAggregate: ' 只读聚合',
    recallName: '记忆',
    practiceName: '练习',
    readingName: '阅读',
    correctRatePrefix: (pct) => `正确率 ${pct}`,
    minutesLabel: '分钟',
    recentTitle: '最近 · RECENT',
    recentDaysLabel: '7 天',
  },
  browse: {
    empty: '暂无卡片',
    emptyHint: '导入或新建卡片',
    restore: '恢复',
    pause: '暂停',
    paused: '已暂停',
    prevCard: '上一张',
    nextCard: '下一张',
  },
  deckDetail: {
    resetProgressTitle: '重置进度',
    resetProgressMessage: (deckName) => `重置「${deckName}」的学习进度？已收藏的卡片会保留。`,
    confirmReset: '确认重置',
    deleteDeckTitle: '删除卡组',
    deleteDeckMessage: '删除此卡组及其所有卡片？此操作不可撤销。',
    confirmDelete: '确认删除',
    batchDeleteTitle: '批量删除',
    batchDeleteMessage: (count) => `删除 ${count} 张卡片？此操作不可撤销。`,
    uncategorized: '未分类',
    rename: '重命名卡组',
    unpinDeck: '取消置顶',
    pinDeck: '置顶卡组',
    finishEditing: '完成编辑',
    batchEditCards: '批量编辑卡片',
    exportDeck: '导出卡组',
    resetProgressMenu: '重置进度',
    deleteDeckMenu: '删除卡组',
    countSuffix: ' 张',
    dueSuffix: ' 待复习',
    learnedSuffix: ' 已学',
    pausedPrefix: '暂停 ',
    weakPrefix: '弱 ',
    midPrefix: '中 ',
    solidPrefix: '稳 ',
    newPrefix: '新 ',
    allFilterPrefix: '全部 · ',
    starredFilter: '收藏',
    listView: '列表',
    treeView: '结构',
    searchPlaceholder: '搜索卡片...',
    batchDeleteLabel: (count) => `删除 (${count})`,
    deleteAllTitle: '全部删除',
    deleteAllMessage: (count) => `删除卡组内全部 ${count} 张卡片？此操作不可撤销。`,
    deleteAllButton: '全部删除',
    dueLeadSuffix: '张 待复习',
    beginLabel: 'BEGIN · 开始',
    browseAction: '浏览',
    reviewAllAction: '全部复习',
    importAction: '导入',
    newCardAction: '新卡片',
    close: '关闭',
    editCard: '编辑',
    deleteCardTitle: '删除卡片',
    deleteCardMessage: '删除这张卡片？此操作不可撤销。',
    deleteCard: '删除',
  },
  flashcardHome: {
    dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
    batchDeleteTitle: '批量删除',
    batchDeleteMessage: (count) => `删除 ${count} 个卡组及其所有卡片？此操作不可撤销。`,
    confirmDelete: '确认删除',
    readyLabel: '准备 · READY',
    todayLabel: '今日 · TODAY',
    pendingImport: '待导入',
    streakSuffix: ' 日',
    decksZh: '卡组',
    dueZh: '待复习',
    cardsZh: '卡片',
    todayZh: '今日',
    totalZh: '总数',
    continueReview: '继续复习',
    dueCountSuffix: ' 张待复习',
    decksTitle: '卡组 · DECKS',
    emptyDecksTitle: '暂无卡组',
    emptyDecksHint: '导入或新建卡组即可开始',
    due: '待复习',
    done: '已完成',
    cardsSuffix: ' 张',
    unpinDeck: '取消置顶',
    pinDeck: '置顶卡组',
    deleteDeckTitle: '删除卡组',
    deleteDeckMessage: (deckName) => `删除卡组「${deckName}」？此操作不可撤销。`,
    deleteDeckMenu: '删除卡组',
    reviewAction: '复习',
    batchDeleteLabel: (count) => `删除 (${count})`,
    deleteAllTitle: '全部删除',
    deleteAllMessage: (count) => `删除全部 ${count} 个卡组及其所有卡片？此操作不可撤销。`,
    deleteAllButton: '全部删除',
    deckNamePlaceholder: '卡组名称',
    add: '添加',
    cancel: '取消',
    importAction: '导入',
    newDeckAction: '新建卡组',
  },
  home: {
    search: '搜索',
    settings: '设置',
    practiceZh: '练习',
    recallZh: '记忆',
    readingZh: '阅读',
  },
  search: {
    uncategorized: '未分类',
    placeholder: '搜索题干或卡片',
    noResults: '没有匹配的内容',
    quizTitle: '题库 · QUIZ',
    flashcardTitle: '闪卡 · FLASHCARD',
    promptTitle: '输入关键词搜索',
    promptHint: '支持中文、英文、LaTeX',
  },
  starred: {
    title: '收藏',
    empty: '暂无收藏',
    emptyHint: '练习时点击星标即可收藏',
    deleteQuestionTitle: '删除题目',
    deleteQuestionMessage: '删除这道题目？此操作不可撤销。',
    confirmDelete: '确认删除',
    deleteQuestion: '删除题目',
  },
  wrong: {
    correctAnswerPrefix: '正确答案：',
    title: '错题本',
    deleteQuestionTitle: '删除题目',
    deleteQuestionMessage: '删除这道题目？此操作不可撤销。',
    confirmDelete: '确认删除',
    defaultDeckName: '错题本',
    subjectDeckNamePrefix: '错题 · ',
    generateFlashcards: '生成闪卡',
    all: '全部',
    empty: '暂无错题',
    emptyHint: '继续保持',
    wrongCountSuffix: (count) => `错${count}次`,
    wrongStreakSuffix: (count) => `连续错${count}次`,
    deleteQuestion: '删除题目',
    redo: '重做',
  },
  quiz: {
    modeRandom: '随机',
    modeSequential: '顺序',
    modeNew: '未做',
    modeWrong: '错题',
    modeStarred: '收藏',
    deleteQuestionTitle: '删除题目',
    deleteQuestionMessage: '删除这道题目？此操作不可撤销。',
    confirmDelete: '确认删除',
    deleteQuestion: '删除题目',
    doneTitle: '一组练毕',
    practicedLabel: '已练',
    correctRateLabel: '正确率',
    correctLabel: '正确',
    wrongLabel: '错误',
    backAction: '返回',
    wrongReviewAction: '错题回顾',
    anotherRoundAction: '再来一组',
    noQuestions: '暂无题目',
  },
  quizHome: {
    justNow: '刚刚',
    minutesAgoSuffix: (mins) => `${mins}分钟前`,
    hoursAgoSuffix: (hours) => `${hours}小时前`,
    daysAgoSuffix: (days) => `${days}天前`,
    continuing: '继续',
    lastPracticeFallback: '上次练习',
    defaultGlyph: '继',
    subjectGlyphFallback: '学',
    choiceCountPrefix: '选择 ',
    reviewCountPrefix: '解答 ',
    wrongSuffix: '错',
    totalSuffix: '题',
    deleteSubjectTitle: '删除科目',
    deleteSubjectMessage: (subjectName) => `删除科目「${subjectName}」及其全部题目与进度？此操作不可撤销。`,
    confirmDelete: '确认删除',
    deleteSubjectAction: '删除科目',
    practiceAction: '练习',
    dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
    readyLabel: '准备 · READY',
    thisWeekLabel: '本周 · THIS WEEK',
    pendingImport: '待导入',
    correctRatePrefix: (pct) => `正确率 ${pct}%`,
    setsZhLabel: '题库',
    wrongZhLabel: '错题',
    questZhLabel: '题目',
    doneZhLabel: '本周',
    totalZhLabel: '总数',
    subjectsHeading: '科目 · SUBJECTS',
    emptySubjectsTitle: '暂无题库',
    emptySubjectsHint: '导入或新建题库即可开始',
    noQuestionsDetected: '未识别到题目。请确认 JSON 格式是否正确。',
    importSummary: (r) => `导入完成！新增: ${r.added}，重复跳过: ${r.duplicates}`,
    importJsonError: '导入失败: JSON 格式错误',
    cancel: '取消',
    importAction: '导入',
    newSubjectAction: '新建题库',
  },
  quizPage: {
    subjectHeadingSuffix: ' · 选择题',
    filterHint: '请更换筛选条件',
    choiceLabel: '选择',
    multiAnswerSuffix: ' · 多选',
    choiceKeyLabel: 'CHOICE',
    multiAnswerBadge: '多选',
    explainHeading: '解析 · WHY',
    correctFeedback: '回答正确。',
    wrongFeedback: '回答错误。',
    submit: '提交',
    nextQuestion: '下一题',
    finishLabel: (correct, total) => `完成 (${correct}/${total})`,
  },
  quizReview: {
    practicedLabel: '已练',
    masteredRateLabel: '掌握率',
    newWrongPrefix: '新增错题 ',
    noMatchingQuestions: '无匹配题目',
    noExplanation: '暂无解析',
    referencePathPrefix: '**参考答案路径:**',
    reviewTagLabel: '解答',
    essayKeyLabel: 'ESSAY',
    referenceKeyLabel: '参考答案 · KEY',
    flipHint: '作答后轻点翻面 · TAP TO REVEAL',
    missedLabel: '未答出',
    gotItLabel: '已掌握',
  },
  quizEngine: {
    questionNotFound: '题目不存在',
    noAnswerGiven: '未作答',
    answerFeedback: (given, expected) => `你的答案: ${given}。正确答案: ${expected}。`,
    noExplanation: '暂无解析',
    solutionPathPrefix: (path) => `参考答案路径: ${path}\n\n`,
  },
  questionParser: {
    skipMissingId: '跳过无效题目: 缺少 id',
    skipMissingType: (id) => `跳过题目 ${id}: 缺少 type`,
    skipUnknownType: (id, type) => `跳过题目 ${id}: 未知类型 "${type}"`,
    noOptionsWarning: (id) => `警告: 选择题 ${id} 没有选项`,
  },
  quizStorage: {
    questionsUnsaved: '题目未保存',
    progressUnsaved: '进度未保存',
    starredUnsaved: '收藏未保存',
    lastSessionUnsaved: '继续练习未保存',
    uncategorized: '未分类',
  },
  setDetail: {
    deleteSubjectTitle: '删除科目',
    deleteSubjectMessage: (subjectName) => `删除科目「${subjectName}」及其全部题目与进度？此操作不可撤销。`,
    confirmDelete: '确认删除',
    resetProgressTitle: '重置进度',
    resetProgressMessage: (subjectName) => `重置「${subjectName}」的练习进度？已收藏的题目会保留。`,
    confirmReset: '确认重置',
    uncategorized: '未分类',
    resetProgressAction: '重置进度',
    deleteSubjectAction: '删除科目',
    totalSuffix: ' 题',
    choicePrefix: '选择 ',
    reviewPrefix: '解答 ',
    allFilterPrefix: '全部 · ',
    choiceFilterPrefix: '选择 · ',
    reviewFilterPrefix: '解答 · ',
    starredFilterPrefix: '收藏 · ',
    listView: '列表',
    treeView: '结构',
    countSuffix: '题',
    choicePrefixShort: '选',
    reviewPrefixShort: '答',
    wrongSuffix: '错',
    choiceTagMini: '选',
    choiceLabelWithCount: (count) => `选择题 (${count}题)`,
    reviewTagMini: '答',
    reviewLabelWithCount: (count) => `解答题 (${count}题)`,
    emptyStarredChapters: '暂无收藏章节',
    emptyChapters: '暂无章节数据',
    beginPracticeLabel: 'BEGIN · 开始练习',
    noQuestions: '暂无题目',
    importFirstLabel: 'IMPORT · 请先导入',
    wrongAction: '错题',
    starredAction: '收藏',
    importAction: '导入',
  },
  readerPanels: {
    tocHeader: '目录 · TOC',
    tocEmpty: '没有可显示的标题',
    highlightsHeader: (count) => `高亮 · HIGHLIGHTS (${count})`,
    highlightsEmpty: '选中文字即可保存高亮',
    delete: '删除',
    bookmarksHeader: (count) => `书签 · BOOKMARKS (${count})`,
    addBookmark: '添加书签',
    bookmarksEmpty: '暂无书签',
    generateFlashcards: '生成闪卡',
    exportHighlightsAction: '导出高亮',
    settingsHeader: '设置 · SETTINGS',
    fontSizeLabel: '字号',
    lineHeightLabel: '行距',
    marginsLabel: '边距',
  },
  reader: {
    highlightsTab: '高亮',
    bookmarksTab: '书签',
    savedHighlightToast: '已保存高亮',
    addedBookmarkToast: '已添加书签',
    exportedHighlightsToast: '已导出高亮',
    flashcardDeckNamePrefix: '阅读 · ',
    flashcardSourceAttribution: (title) => `\n\n——《${title}》`,
    loading: '加载中...',
    saveHighlight: '保存高亮',
    settings: '设置',
  },
  readingHome: {
    deleteCollectionTitle: '删除集合',
    deleteCollectionMessage: (name) => `删除集合「${name}」及其所有文档？此操作不可撤销。`,
    confirmDelete: '确认删除',
  },
  readingHomeBody: {
    noMatchingDocs: '没有匹配的文档',
    searchResultsHeading: '搜索结果',
    readyLabel: '准备 · READY',
    thisWeekLabel: '本周 · THIS WEEK',
    pendingImport: '待导入',
    minutesSuffix: (mins) => `${mins} 分钟`,
    colsZhLabel: '集合',
    minZhLabel: '分钟',
    docsZhLabel: '文档',
    doneZhLabel: '完成',
    continueReading: '继续阅读',
    collectionsHeading: '集合 · COLLECTIONS',
    createdSort: '创建',
    recentSort: '最近',
    emptyCollectionsTitle: '还没有阅读集合',
    emptyCollectionsHint: '导入或新建集合即可开始阅读',
    docsCountSuffix: ' 篇文档',
    unpinCollection: '取消置顶',
    pinCollection: '置顶集合',
    deleteCollection: '删除集合',
    readAction: '阅读',
    newDocHeading: '新建文档',
    docTitlePlaceholder: '文档标题',
    docContentPlaceholder: '文档内容（Markdown）',
    cancel: '取消',
    create: '创建',
    newColNamePlaceholder: '集合名称',
    importAction: '导入',
    newCollectionAction: '新建集合',
  },
  readingHomePage: {
    title: '阅读',
    searchPlaceholder: '搜索文档标题或内容',
  },
  readingHomeContent: {
    searchPlaceholder: '搜索文档',
  },
  collectionDetail: {
    importFailedToast: '文件导入失败，请检查文件格式',
    deleteDocTitle: '删除文档',
    deleteDocMessage: '删除这篇文档？此操作不可撤销。',
    confirmDelete: '确认删除',
    deleteCollectionTitle: '删除集合',
    deleteCollectionMessage: (name) => `删除集合「${name}」及其所有文档？此操作不可撤销。`,
    notFound: '集合未找到',
    unpinCollection: '取消置顶',
    pinCollection: '置顶集合',
    deleteCollection: '删除集合',
    docsCountSuffix: ' 篇文档',
    recentSort: '最近',
    titleSort: '标题',
    createdSort: '创建',
    emptyDocs: '暂无文档',
    emptyDocsHint: '导入或新建文档',
    newDocHeading: '新建文档',
    docTitlePlaceholder: '文档标题',
    docContentPlaceholder: '文档内容（Markdown）',
    cancel: '取消',
    create: '创建',
    continueReadingSuffix: 'CONTINUE · 继续阅读',
    emptyDocsLead: '暂无文档',
    importFirstSuffix: 'IMPORT · 请先导入',
    importAction: '导入',
    newAction: '新建',
  },
  bookmarks: {
    defaultTitle: (scrollPct) => `书签 · ${scrollPct}%`,
  },
  exportHighlights: {
    titleHeading: (title) => `# ${title} · 高亮导出`,
    countLine: (count, date) => `> ${count} 条高亮 · ${date}`,
    otherHeading: '## 其他',
  },
  readingStats: {
    dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
  },
  readingStorage: {
    unsaved: (key) => `${key} 未保存`,
  },
}
