export const activity = {
  todayTitle: '今日',
  todayCompletionAria: (percentValue) => `今日完成度 ${percentValue}%`,
  percentLabel: '完成度',
  recallRingLabel: '记忆 · ',
  practiceRingLabel: '练习 · ',
  readingRingLabel: '阅读 · ',
  dayLabelsShort: ['日', '一', '二', '三', '四', '五', '六'],
  monthNames: ['', '1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  heatmapTitle: '热力',
  heatmapDays: '90 天',
  recallDetailPrefix: '记忆 ',
  practiceDetailPrefix: '练习 ',
  readingDetailPrefix: '阅读 ',
  back: '返回',
  pageTitle: '活动',
  thisMonth: '本月',
  monthLabel: '本月',
  streakSuffix: ' 日连续',
  activeDaysLabel: '活跃天数',
  thisWeekLabel: '本周活动',
  totalLabel: '总活动量',
  calendarTitle: '月历',
  calendarDaysSuffix: ' 天',
  modulesTitle: '模块',
  readonlyAggregate: ' 只读聚合',
  recallName: '记忆',
  practiceName: '练习',
  readingName: '阅读',
  correctRatePrefix: (pct) => `正确率 ${pct}`,
  minutesLabel: '分钟',
  recentTitle: '最近',
  recentDaysLabel: '7 天',
}
