export const collectionDetail = {
  closeMenu: '关闭菜单',
  importFailedToast: '文件导入失败，请检查文件格式',
  deleteDocTitle: '删除文档',
  deleteDocMessage: '删除这篇文档？此操作不可撤销。',
  confirmDelete: '确认删除',
  deleteCollectionTitle: '删除集合',
  deleteCollectionMessage: (name) => `删除集合「${name}」及其所有文档？此操作不可撤销。`,
  notFound: '集合未找到',
  unpinCollection: '取消置顶',
  pinCollection: '置顶集合',
  deleteCollection: '删除集合',
  docsCountSuffix: ' 篇文档',
  recentSort: '最近',
  titleSort: '标题',
  createdSort: '创建',
  emptyDocs: '暂无文档',
  emptyDocsHint: '导入或新建文档',
  newDocHeading: '新建文档',
  docTitlePlaceholder: '文档标题',
  docContentPlaceholder: '文档内容（Markdown）',
  cancel: '取消',
  create: '创建',
  continueReadingSuffix: '继续阅读',
  emptyDocsLead: '暂无文档',
  importFirstSuffix: '请先导入',
  importAction: '导入',
  newAction: '新建',
}
