export const deckDetail = {
  closeMenu: '关闭菜单',
  resetProgressTitle: '重置进度',
  resetProgressMessage: (deckName) => `重置「${deckName}」的学习进度？已收藏的卡片会保留。`,
  confirmReset: '确认重置',
  deleteDeckTitle: '删除卡组',
  deleteDeckMessage: '删除此卡组及其所有卡片？此操作不可撤销。',
  confirmDelete: '确认删除',
  batchDeleteTitle: '批量删除',
  batchDeleteMessage: (count) => `删除 ${count} 张卡片？此操作不可撤销。`,
  uncategorized: '未分类',
  rename: '重命名卡组',
  unpinDeck: '取消置顶',
  pinDeck: '置顶卡组',
  finishEditing: '完成编辑',
  batchEditCards: '批量编辑卡片',
  exportDeck: '导出卡组',
  resetProgressMenu: '重置进度',
  deleteDeckMenu: '删除卡组',
  countSuffix: ' 张',
  dueSuffix: ' 待复习',
  learnedSuffix: ' 已学',
  pausedPrefix: '暂停 ',
  weakPrefix: '弱 ',
  midPrefix: '中 ',
  solidPrefix: '稳 ',
  newPrefix: '新 ',
  allFilterPrefix: '全部 · ',
  starredFilter: '收藏',
  listView: '列表',
  treeView: '结构',
  searchPlaceholder: '搜索卡片...',
  batchDeleteLabel: (count) => `删除 (${count})`,
  deleteAllTitle: '全部删除',
  deleteAllMessage: (count) => `删除卡组内全部 ${count} 张卡片？此操作不可撤销。`,
  deleteAllButton: '全部删除',
  dueLeadSuffix: '张 待复习',
  beginLabel: '开始',
  browseAction: '浏览',
  reviewAllAction: '全部复习',
  importAction: '导入',
  newCardAction: '新卡片',
  close: '关闭',
  editCard: '编辑',
  deleteCardTitle: '删除卡片',
  deleteCardMessage: '删除这张卡片？此操作不可撤销。',
  deleteCard: '删除',
}
