export const deckDetail = {
  /* 熟练度分布表（记-31）——替旧四件同源之物 */
  distributionLabel: '熟练度',
  totalSummary: (total, learned) => `共 ${total} 张 · 已学 ${learned}`,
  solidTier: '稳',
  midTier: '中',
  weakTier: '弱',
  newTier: '新',
  pausedTier: '暂停',
  referenceTier: '资料',
  focusLabel: '本卡组',
  dueUnit: '张待复习',
  focusSummary: (total, ago) => `共 ${total} 张 · ${ago}`,
  neverReviewed: '未复习',
  justReviewed: '刚刚复习',
  minutesAgo: (n) => `${n} 分钟前复习`,
  hoursAgo: (n) => `${n} 小时前复习`,
  daysAgo: (n) => `${n} 天前复习`,
  startReviewAction: '开始复习',
  notFound: '卡组未找到',
  notFoundHint: '它可能已被删除或尚未导入',
  emptyCardsTitle: '暂无卡片',
  emptyCardsHint: '新建或导入卡片即可开始',
  closeMenu: '关闭菜单',
  resetProgressTitle: '重置进度',
  resetProgressMessage: (deckName) => `重置「${deckName}」的学习进度？已收藏的卡片会保留。`,
  confirmReset: '确认重置',
  deleteDeckTitle: '删除卡组',
  deleteDeckMessage: '删除此卡组及其所有卡片？此操作不可撤销。',
  confirmDelete: '确认删除',
  batchDeleteTitle: '批量删除',
  batchDeleteMessage: (count) => `删除 ${count} 张卡片？此操作不可撤销。`,
  uncategorized: '未分类',
  rename: '重命名卡组',
  unpinDeck: '取消置顶',
  pinDeck: '置顶卡组',
  finishEditing: '完成编辑',
  batchEditCards: '批量编辑卡片',
  exportDeck: '导出卡组',
  resetProgressMenu: '重置进度',
  deleteDeckMenu: '删除卡组',
  countSuffix: ' 张',
  dueSuffix: ' 待复习',
  learnedSuffix: ' 已学',
  pausedPrefix: '暂停 ',
  weakPrefix: '弱 ',
  midPrefix: '中 ',
  solidPrefix: '稳 ',
  newPrefix: '新 ',
  allFilterPrefix: '全部 · ',
  starredFilter: '收藏',
  filterLabel: '筛选卡片',
  allFilter: (count) => `全部 ${count}`,
  dueFilter: (count) => `待复习 ${count}`,
  starredFilterCount: (count) => `收藏 ${count}`,
  wrongFilter: (count) => `错题 ${count}`,
  filterEmpty: '这一筛选下没有卡片',
  listView: '列表',
  treeView: '结构',
  searchPlaceholder: '搜索卡片...',
  batchDeleteLabel: (count) => `删除 (${count})`,
  deleteAllTitle: '全部删除',
  deleteAllMessage: (count) => `删除卡组内全部 ${count} 张卡片？此操作不可撤销。`,
  deleteAllButton: '全部删除',
  dueLeadSuffix: '张 待复习',
  progressLabel: '进度',
  beginLabel: '开始',
  browseAction: '浏览',
  reviewAllAction: '全部复习',
  importAction: '导入',
  newCardAction: '新卡片',
  previewFrontLabel: '问',
  previewBackLabel: '答',
  close: '关闭',
  editCard: '编辑',
  deleteCardTitle: '删除卡片',
  deleteCardMessage: '删除这张卡片？此操作不可撤销。',
  deleteCard: '删除',
}
