export const flashcardHome = {
  dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
  /* 焦点行（版1）：一个主数、一句分解、一个去处。
     旧「总数」「今日」两量已下沉活动页——用户不因「总数 3」做任何事。 */
  todayLabel: '今日',
  readyLabel: '准备',
  dueUnit: ' 张待复习',
  emptyUnit: ' 个卡组',
  startReviewAction: '开始复习',
  reviewAllAction: '复习全部',
  /* 分解句：只列前二，第三个之後对「先做哪个」已无帮助 */
  breakdownJoin: ' · ',
  breakdownItem: (name, n) => `${name} ${n}`,
  forecastTitle: '未来七日到期',
  forecastTotal: (n) => `合计 ${n}`,
  activityLink: '活动',
  continueReview: '继续复习',
  dismissContinue: '不再提示',
  dueCountSuffix: ' 张待复习',
  decksTitle: '卡组',
  emptyDecksTitle: '暂无卡组',
  emptyDecksHint: '导入或新建卡组即可开始',
  done: '已清',
  weakPrefix: '弱 ',
  masteryLabel: (solid, total) => `稳 ${solid}/${total}`,
  neverReviewed: '未复习',
  reviewedAgo: (ago) => `${ago}复习`,
  justNow: '刚刚',
  minutesAgo: (n) => `${n} 分钟前`,
  hoursAgo: (n) => `${n} 小时前`,
  daysAgo: (n) => `${n} 天前`,
  deckNamePlaceholder: '卡组名称',
  add: '添加',
  cancel: '取消',
  importAction: '导入',
  newDeckAction: '新建卡组',
  creatingDeck: '新建中',
  deckCreated: '已新建',
  createRetry: '重试新建',
  createFailed: '卡组名称不能为空。',
}
