export const flashcardHome = {
  dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
  batchDeleteTitle: '批量删除',
  batchDeleteMessage: (count) => `删除 ${count} 个卡组及其所有卡片？此操作不可撤销。`,
  confirmDelete: '确认删除',
  readyLabel: '准备',
  todayLabel: '今日',
  pendingImport: '待导入',
  streakSuffix: ' 日',
  decksZh: '卡组',
  dueZh: '待复习',
  cardsZh: '卡片',
  todayZh: '今日',
  totalZh: '总数',
  continueReview: '继续复习',
  dueCountSuffix: ' 张待复习',
  decksTitle: '卡组',
  emptyDecksTitle: '暂无卡组',
  emptyDecksHint: '导入或新建卡组即可开始',
  due: '待复习',
  done: '已完成',
  cardsSuffix: ' 张',
  unpinDeck: '取消置顶',
  pinDeck: '置顶卡组',
  deleteDeckTitle: '删除卡组',
  deleteDeckMessage: (deckName) => `删除卡组「${deckName}」？此操作不可撤销。`,
  deleteDeckMenu: '删除卡组',
  reviewAction: '复习',
  batchDeleteLabel: (count) => `删除 (${count})`,
  deleteAllTitle: '全部删除',
  deleteAllMessage: (count) => `删除全部 ${count} 个卡组及其所有卡片？此操作不可撤销。`,
  deleteAllButton: '全部删除',
  deckNamePlaceholder: '卡组名称',
  add: '添加',
  cancel: '取消',
  importAction: '导入',
  newDeckAction: '新建卡组',
}
