export const home = {
  search: '搜索',
  settings: '设置',
  todayTab: '今日',
  materialsTab: '资料',
  activityTab: '活动',
  materialsFilter: '资料类型',
  materialKinds: {
    flashcard: '记忆',
    quiz: '练习',
    reading: '阅读',
  },
  today: {
    emptyTitle: '先放入一份学习材料',
    emptyHint: '导入卡片、题目或文档后，Mnemos 会把下一步排成一条今日路径。',
    importAction: '导入资料',
    openMaterials: '查看资料',
    pendingTitle: (count) => `${count} 项待继续`,
    completeTitle: '今日已清',
    completeHint: '没有中断现场，也没有到期、错题或未读完资料。',
    primaryHint: (primary) => primary?.title ? `从「${primary.title}」接上` : '从最合适的一步开始',
    nextLabel: '接下来',
    pathTitle: '今日路径',
    pathNote: '按当前状态排序',
    stageLabel: { recall: '复习', practice: '订正', reading: '阅读' },
    stageCount: {
      recall: (count) => `${count} 张到期卡片`,
      practice: (count) => `${count} 道错题`,
      reading: (count) => `${count} 篇未读完`,
    },
    resumeStage: (title) => title ? `继续「${title}」` : '恢复上次现场',
    readingProgress: (title, progress) => `继续「${title}」 · ${progress}%`,
    cleared: '已清',
    later: '随后',
    materialsLink: '查看全部资料',
    resumeAction: { recall: '继续复习', practice: '继续练习', reading: '继续阅读' },
    startAction: { recall: '开始复习', practice: '订正错题', reading: '继续阅读' },
  },
  practiceZh: '练习',
  recallZh: '记忆',
  readingZh: '阅读',
}
