export const importStrings = {
  jsonParseError: '导入失败: JSON 格式错误',
  unrecognizedJsonFormat: '导入失败: 无法识别的 JSON 格式',
  replaceAllTitle: '替换全部',
  replaceAllQuizMessage: '替换全部会覆盖当前所有练习数据，此操作不可撤销。',
  confirmReplace: '确认替换',
  importedQuestionsCount: (count) => `导入完成！题目: ${count}`,
  importSummaryWithMerge: (added, duplicates, merged) => `导入完成！新增: ${added}，重复跳过: ${duplicates}，合并进度: ${merged}`,
  importSummary: (added, duplicates) => `导入完成！新增: ${added}，重复跳过: ${duplicates}`,
  noCardsDetected: '未识别到卡片。支持 MD 列表、Anki 导出的 txt/csv，或纯文本按「正面换行背面」成组输入。',
  importedDeckSummary: (deckName, cardCount, dupSuffix) => `导入完成！卡组: ${deckName}，卡片: ${cardCount}${dupSuffix}`,
  skippedDuplicatesSuffix: (count) => `，跳过重复: ${count}`,
  replaceAllDataMessage: '替换全部会覆盖当前所有数据，此操作不可撤销。',
  importFailed: '导入失败',
  selectOrCreateCollection: '请选择或创建一个集合',
  importedDocSummary: (title, format) => `导入完成！文档: ${title}，格式: ${format}`,
  quizBackupPreviewTitle: '练习备份预览',
  jsonImportPreviewTitle: 'JSON 导入预览',
  importModeHeading: '导入方式',
  mergeData: '合并数据',
  replaceAll: '替换全部',
  replaceAllQuizNote: '替换全部会覆盖当前所有练习数据。确认导入前还会再次询问。',
  questionBankStatsHeading: '题库统计',
  totalQuestionsLabel: '总题数',
  choiceTypeLabel: '选择',
  essayTypeLabel: '解答',
  subjectDistributionHeading: '科目分布',
  countSuffix: (count) => `${count} 题`,
  warningHeading: (count) => `警告 (${count})`,
  cancel: '取消',
  confirmImport: '确认导入',
  currentDecksLabel: '当前卡组',
  currentCardsLabel: '当前卡片',
  importedDecksLabel: '导入卡组',
  importedCardsLabel: '导入卡片',
  replaceAllDecksNote: '替换全部会覆盖当前所有卡组和卡片。确认导入前还会再次询问。',
  fullBackupPreviewTitle: '完整备份预览',
  replaceAllFullNote: '替换全部会覆盖当前所有数据。确认导入前还会再次询问。',
  recallHeading: '记忆 · RECALL',
  decksLabel: '卡组',
  cardsLabel: '卡片',
  practiceHeading: '练习 · PRACTICE',
  questionsLabel: '题目',
  progressLabel: '进度',
  readingHeading: '阅读 · READING',
  collectionsLabel: '文集',
  documentsLabel: '文档',
  mdPreviewTitle: 'MD 导入预览',
  importToDeckLabel: '导入到卡组',
  deckNameLabel: '卡组名称',
  parsedCardsLabel: '解析卡片',
  duplicateCardsLabel: '重复卡片',
  skipDuplicates: '跳过重复',
  importAll: '全部导入',
  willImportLabel: '将导入',
  cardPreviewHeading: '卡片预览',
  ellipsis: '···',
  andMoreCardsSuffix: (count) => `还有 ${count} 张`,
  readingDocPreviewTitle: '阅读文档预览',
  docInfoHeading: '文档信息',
  titleLabel: '标题',
  formatLabel: '格式',
  sizeLabel: '大小',
  sizeCharsSuffix: (count) => `${count} 字符`,
  importToCollectionHeading: '导入到集合',
  selectCollectionPlaceholder: '选择集合...',
  orCreateNewLabel: '或新建',
  newCollectionNamePlaceholder: '新集合名称',
  pageTitle: '导入',
  quizTabLabel: '做题 · JSON',
  mdTabLabel: '闪卡 · MD',
  readingTabLabel: '阅读 · DOC',
  quizImportHeading: '做题导入 · PRACTICE',
  targetLabel: '目标',
  quizTargetValue: '按科目与章节练习',
  contentLabel: '内容',
  quizContentValue: '选择题 / 解答题',
  afterImportLabel: '导入后',
  quizAfterImportValue: '进入练习模块',
  fileImportHeading: '文件导入 · FILE',
  clickOrDropFile: '点击选择 · 或拖入文件',
  supportedFormatHeading: '支持格式 · FORMAT',
  questionBankFileLabel: '题库文件',
  splitByChapterLabel: '按章节拆分',
  jsonFileLabel: 'JSON 文件',
  questionTypesHeading: '题目类型 · TYPES',
  choiceLabel: '选择',
  essayLabel: '解答',
  readingImportHeading: '阅读导入 · READING',
  readingTargetValue: '长文阅读与标注',
  readingContentValue: '文档 / 讲义 / 笔记',
  readingAfterImportValue: '放入阅读集合',
  pasteContentHeading: '粘贴内容',
  pasteMarkdownPlaceholder: '直接粘贴 Markdown 内容',
  previewDoc: '预览文档',
  plainTextLabel: '纯文本',
  restoreImportHeading: '恢复备份 · RESTORE',
  restoreTargetValue: '恢复完整备份 / 仅记忆 / 仅练习',
  sourceLabel: '来源',
  restoreSourceValue: 'Settings 导出的备份文件',
  modeLabel: '模式',
  restoreModeValue: '合并数据 或 替换全部',
  clickOrDropBackupFile: '点击选择 · 或拖入备份文件',
  fullBackupLabel: '完整备份',
  fullBackupFormatsValue: '记忆 + 练习 + 阅读',
  flashcardOnlyLabel: '仅记忆',
  flashcardOnlyValue: '卡组和卡片',
  quizOnlyLabel: '仅练习',
  quizOnlyValue: '题目、进度和收藏',
  autoBackupLocationNote: '自动备份文件位于 Documents/Mnemos/',
  flashcardImportHeading: '闪卡导入 · RECALL',
  flashcardTargetValue: '间隔复习与主动回忆',
  flashcardContentValue: '正面 / 背面卡片',
  appendToDeckSuffix: (deckName) => `追加到「${deckName}」`,
  generateNewDeck: '生成卡组',
  pasteFlashcardPlaceholder: '# 章节&#10;## 小节&#10;* 正面&#10;  * 背面要点&#10;&#10;也支持 Anki 导出的 txt/csv 格式',
  parseAndPreview: '解析并预览',
  markdownListLabel: '.md 列表',
  ankiExportLabel: 'Anki 导出',
  ankiExportFormatValue: 'txt / csv，含 cloze',
  plainTextFrontBackValue: '正面换行背面',
  notSureHowToPrepare: '不知如何准备？ ',
  viewCardGuideLink: '查看制卡指南 →',
  manageInReadingNote: '导入后可在「阅读」模块管理',
  restoreEntryLabel: '恢复备份 · RESTORE',
  restoreEntryDetail: '完整 / 仅记忆 / 仅练习',
}
