export const quizHome = {
  justNow: '刚刚',
  minutesAgoSuffix: (mins) => `${mins}分钟前`,
  hoursAgoSuffix: (hours) => `${hours}小时前`,
  daysAgoSuffix: (days) => `${days}天前`,
  continuing: '继续',
  lastPracticeFallback: '上次练习',
  defaultGlyph: '继',
  subjectGlyphFallback: '学',
  choiceCountPrefix: '选择 ',
  reviewCountPrefix: '解答 ',
  wrongSuffix: '错',
  totalSuffix: '题',
  deleteSubjectTitle: '删除科目',
  deleteSubjectMessage: (subjectName) => `删除科目「${subjectName}」及其全部题目与进度？此操作不可撤销。`,
  confirmDelete: '确认删除',
  deleteSubjectAction: '删除科目',
  practiceAction: '练习',
  dayLabels: ['日', '一', '二', '三', '四', '五', '六'],
  readyLabel: '准备 · READY',
  thisWeekLabel: '本周 · THIS WEEK',
  pendingImport: '待导入',
  correctRatePrefix: (pct) => `正确率 ${pct}%`,
  setsZhLabel: '题库',
  wrongZhLabel: '错题',
  questZhLabel: '题目',
  doneZhLabel: '本周',
  totalZhLabel: '总数',
  subjectsHeading: '科目 · SUBJECTS',
  emptySubjectsTitle: '暂无题库',
  emptySubjectsHint: '导入或新建题库即可开始',
  noQuestionsDetected: '未识别到题目。请确认 JSON 格式是否正确。',
  importSummary: (r) => `导入完成！新增: ${r.added}，重复跳过: ${r.duplicates}`,
  importJsonError: '导入失败: JSON 格式错误',
  cancel: '取消',
  importAction: '导入',
  newSubjectAction: '新建题库',
}
