export const quizHome = {
  justNow: '刚刚',
  minutesAgoSuffix: (mins) => `${mins} 分钟前`,
  hoursAgoSuffix: (hours) => `${hours} 小时前`,
  daysAgoSuffix: (days) => `${days} 天前`,
  /* 焦点行：错题是这一屏唯一有「下一步」的数。旧式并列
     「错题 / 本周 / 总数」三格，其中「总数」不支持任何决策。 */
  readyLabel: '准备',
  wrongLabel: '错题',
  libraryLabel: '题库',
  emptyUnit: ' 个题库',
  wrongUnit: ' 题待订正',
  questionUnit: ' 道题',
  allClearHint: '错题已清',
  practiceWrongAction: '练错题',
  startPracticeAction: '开始练习',
  activityLink: '活动',
  continuing: '继续',
  dismissContinue: '不再提示',
  lastPracticeFallback: '上次练习',
  progressLabel: (done, total) => `已做 ${done}/${total}`,
  practicedAgo: (ago) => `${ago}练习`,
  noWrong: '已清',
  subjectsHeading: '科目',
  emptySubjectsTitle: '暂无题库',
  emptySubjectsHint: '导入或新建题库即可开始',
  jsonPlaceholder: '粘贴题目 JSON（数组，每项含 id / type / subject / question / answer）',
  noQuestionsDetected: '未识别到题目。请确认 JSON 是数组，且每项含 question 与 answer。',
  importing: '导入中',
  imported: '已导入',
  /* 同上（记-32）；带上道数，方是这一次导入之实。 */
  importedNotice: (count) => `已导入 ${count} 道题`,
  importRetry: '重试导入',
  cancel: '取消',
  importAction: '导入',
  newSubjectAction: '新建题库',
}
