export const quiz = {
  modeRandom: '随机',
  modeSequential: '顺序',
  modeNew: '未做',
  modeWrong: '错题',
  modeStarred: '收藏',
  deleteQuestionTitle: '删除题目',
  deleteQuestionMessage: '删除这道题目？此操作不可撤销。',
  confirmDelete: '确认删除',
  deleteQuestion: '删除题目',
  doneTitle: '一组练毕',
  practicedLabel: '已练',
  correctRateLabel: '正确率',
  correctLabel: '正确',
  wrongLabel: '错误',
  backAction: '返回',
  wrongReviewAction: '错题回顾',
  anotherRoundAction: '再来一组',
  noQuestions: '暂无题目',
}
