export const quizPage = {
  back: '返回',
  closeMenu: '关闭菜单',
  starQuestion: '收藏题目',
  unstarQuestion: '取消收藏题目',
  subjectHeadingSuffix: ' · 选择题',
  filterHint: '请更换筛选条件',
  choiceLabel: '选择',
  multiAnswerSuffix: ' · 多选',
  multiAnswerBadge: '多选',
  explainHeading: '解析',
  correctFeedback: '回答正确。',
  wrongFeedback: '回答错误。',
  submit: '提交',
  nextQuestion: '下一题',
  finishLabel: (correct, total) => `完成 (${correct}/${total})`,
}
