export const quizReview = {
  back: '返回',
  closeMenu: '关闭菜单',
  practicedLabel: '已练',
  masteredRateLabel: '掌握率',
  newWrongPrefix: '新增错题 ',
  noMatchingQuestions: '无匹配题目',
  noExplanation: '暂无解析',
  referencePathPrefix: '**参考答案路径:**',
  reviewTagLabel: '解答',
  referenceMark: '参',
  flipHint: '作答后轻点翻面',
  missedLabel: '未答出',
  gotItLabel: '已掌握',
}
