export const readingHomeBody = {
  noMatchingDocs: '没有匹配的文档',
  searchResultsHeading: '搜索结果',
  readyLabel: '准备',
  thisWeekLabel: '本周',
  pendingImport: '待导入',
  minutesSuffix: (mins) => `${mins} 分钟`,
  colsZhLabel: '集合',
  minZhLabel: '分钟',
  docsZhLabel: '文档',
  doneZhLabel: '完成',
  continueReading: '继续阅读',
  collectionsHeading: '集合',
  createdSort: '创建',
  recentSort: '最近',
  emptyCollectionsTitle: '还没有阅读集合',
  emptyCollectionsHint: '导入或新建集合即可开始阅读',
  docsCountSuffix: ' 篇文档',
  unpinCollection: '取消置顶',
  pinCollection: '置顶集合',
  deleteCollection: '删除集合',
  readAction: '阅读',
  newDocHeading: '新建文档',
  docTitlePlaceholder: '文档标题',
  docContentPlaceholder: '文档内容（Markdown）',
  cancel: '取消',
  create: '创建',
  newColNamePlaceholder: '集合名称',
  importAction: '导入',
  newCollectionAction: '新建集合',
}
