export const reader = {
  notFound: '文档未找到',
  loadErrorTitle: '文档载入失败',
  loadErrorHint: '内容读取出错，可重试或返回',
  retryAction: '重试',
  tocTab: '目录',
  highlightsTab: '高亮',
  bookmarksTab: '书签',
  savedHighlightToast: '已保存高亮',
  addedBookmarkToast: '已添加书签',
  exportedHighlightsToast: '已导出高亮',
  flashcardDeckNamePrefix: '阅读 · ',
  flashcardSourceAttribution: (title) => `\n\n——《${title}》`,
  loading: '加载中...',
  saveHighlight: '保存高亮',
  settings: '设置',
  fontSizeSetting: '字号',
  lineHeightSetting: '行距',
  marginsSetting: '边距',
  decreaseFontSize: '减小字号',
  increaseFontSize: '增大字号',
  decreaseLineHeight: '减小行距',
  increaseLineHeight: '增大行距',
  decreaseMargins: '减小边距',
  increaseMargins: '增大边距',
}
