export const readerPanels = {
  tocHeader: '目录',
  tocEmpty: '没有可显示的标题',
  highlightsHeader: (count) => `高亮 (${count})`,
  highlightsEmpty: '选中文字即可保存高亮',
  delete: '删除',
  bookmarksHeader: (count) => `书签 (${count})`,
  addBookmark: '添加书签',
  bookmarksEmpty: '暂无书签',
  generateFlashcards: '生成闪卡',
  exportHighlightsAction: '导出高亮',
  settingsHeader: '设置',
  fontSizeLabel: '字号',
  lineHeightLabel: '行距',
  marginsLabel: '边距',
}
