export const readingHomeBody = {
  noMatchingDocs: '没有匹配的文档',
  searchHint: '换个词试试，或清空搜索框回到集合列表',
  /* 焦点行：未读完的篇数是这一屏唯一有「下一步」的数。
     旧式并列「分钟 / 完成 / 文档」三格——分钟是回顾不是决策。 */
  readyLabel: '准备',
  readingLabel: '阅读',
  emptyUnit: ' 个集合',
  pendingUnit: ' 篇未读完',
  weekSummary: (mins, docs) => `本周 ${mins} 分钟 · 共 ${docs} 篇`,
  startReadingAction: '开始阅读',
  continueReading: '继续阅读',
  dismissContinue: '不再提示',
  activityLink: '活动',
  collectionsHeading: '集合',
  createdSort: '创建',
  recentSort: '最近',
  emptyCollectionsTitle: '还没有阅读集合',
  emptyCollectionsHint: '导入或新建集合即可开始阅读',
  docsProgress: (done, total) => `已读完 ${done}/${total}`,
  allRead: '已读完',
  unpinCollection: '取消置顶',
  pinCollection: '置顶集合',
  deleteCollection: '删除集合',
  newDocHeading: '新建文档',
  docTitlePlaceholder: '文档标题',
  docContentPlaceholder: '文档内容（Markdown）',
  cancel: '取消',
  create: '创建',
  creating: '创建中',
  created: '已创建',
  createRetry: '重试创建',
  nameRequired: '集合名称不能为空。',
  newColNamePlaceholder: '集合名称',
  importAction: '导入',
  newCollectionAction: '新建集合',
}
