export const review = {
  /* 完成屏之关系式（记-31）——替旧「Mnēmosúnē 大标 + 两孤立数 + 四格计数」 */
  doneTitle: '这一轮做完了',
  doneSummary: (n, dur) => `${n} 张 · ${dur}`,
  durationInstant: '不到一秒',
  durationSecs: (s) => `${s} 秒`,
  durationMins: (m, s) => (s > 0 ? `${m} 分 ${s} 秒` : `${m} 分`),
  vsLast: '较上次',
  deltaCards: (n) => (n > 0 ? `多 ${n} 张` : n < 0 ? `少 ${-n} 张` : '张数相同'),
  deltaPct: (n) => (n > 0 ? ` ↑${n}` : n < 0 ? ` ↓${-n}` : ''),
  againCount: (n) => `${n} 张`,
  nextDue: '下次到期',
  nextDueValue: (date, count) => `${date} · ${count} 张`,
  continueNext: (name) => `继续 ${name}`,
  again: '重来',
  remember: '记住',
  flipHint: '轻点翻面',
  hard: '困难',
  easy: '容易',
  later: '稍后', // used as a control-flow sentinel via === in Review.jsx's predictInterval(), not decorative-only text
  title: '复习',
  doneZh: '今日复习完成',
  reviewedCount: '已复习',
  correctRate: '正确率',
  undoLastCard: '撤销上一张',
  backToDeck: '返回卡组',
  browseCards: '浏览卡片',
  leechToast: '卡片已标记为顽固卡并暂停',
  ratedToastPrefix: '已評分 · ',
  undoToast: '已撤销',
  undoToastLabel: '撤销',
  learningPrefix: '学习中 · ',
}
