export const review = {
  again: '重来',
  remember: '记住',
  flipHint: '轻点翻面',
  hard: '困难',
  easy: '容易',
  later: '稍后', // used as a control-flow sentinel via === in Review.jsx's predictInterval(), not decorative-only text
  title: '复习',
  doneZh: '今日复习完成',
  reviewedCount: '已复习',
  correctRate: '正确率',
  undoLastCard: '撤销上一张',
  backToDeck: '返回卡组',
  browseCards: '浏览卡片',
  leechToast: '卡片已标记为顽固卡并暂停',
  ratedToastPrefix: '已評分 · ',
  undoToast: '已撤銷',
  undoToastLabel: '撤销',
  learningPrefix: '学习中 · ',
}
