export const setDetail = {
  deleteSubjectTitle: '删除科目',
  deleteSubjectMessage: (subjectName) => `删除科目「${subjectName}」及其全部题目与进度？此操作不可撤销。`,
  confirmDelete: '确认删除',
  resetProgressTitle: '重置进度',
  resetProgressMessage: (subjectName) => `重置「${subjectName}」的练习进度？已收藏的题目会保留。`,
  confirmReset: '确认重置',
  uncategorized: '未分类',
  resetProgressAction: '重置进度',
  deleteSubjectAction: '删除科目',
  totalSuffix: ' 题',
  choicePrefix: '选择 ',
  reviewPrefix: '解答 ',
  allFilterPrefix: '全部 · ',
  choiceFilterPrefix: '选择 · ',
  reviewFilterPrefix: '解答 · ',
  starredFilterPrefix: '收藏 · ',
  listView: '列表',
  treeView: '结构',
  countSuffix: '题',
  choicePrefixShort: '选',
  reviewPrefixShort: '答',
  wrongSuffix: '错',
  choiceTagMini: '选',
  choiceLabelWithCount: (count) => `选择题 (${count}题)`,
  reviewTagMini: '答',
  reviewLabelWithCount: (count) => `解答题 (${count}题)`,
  emptyStarredChapters: '暂无收藏章节',
  emptyChapters: '暂无章节数据',
  beginPracticeLabel: 'BEGIN · 开始练习',
  noQuestions: '暂无题目',
  importFirstLabel: 'IMPORT · 请先导入',
  wrongAction: '错题',
  starredAction: '收藏',
  importAction: '导入',
}
