export const settings = {
  quarantineMissing: '隔离数据不存在',
  discardQuarantineTitle: '丢弃受损数据',
  discardQuarantineMessage: (key) => `丢弃 ${key} 的隔离副本？请确认已经导出或不再需要它。`,
  confirmDiscard: '确认丢弃',
  quarantineDiscarded: '已丢弃隔离数据',
  title: '设置',
  appearanceHeading: '外观',
  demoContentHeading: '示例内容',
  demoContentTitle: '载入示例内容包',
  demoContentDetail: '加入一组自撰记忆卡、练习题和阅读文档，用来预览完整流程',
  demoContentAction: '载入',
  demoContentAddedToast: (count) => count > 0 ? `已载入 ${count} 项示例内容` : '示例内容已存在',
  recallHeading: '记忆',
  decksLabel: '卡组',
  cardsLabel: '卡片',
  dueLabel: '待复习',
  dailyLimitTitle: '每日上限',
  dailyLimitHint: '限定记忆卡当天复习数量',
  dailyLimitPlaceholder: '不限',
  dataGroupTitle: '数据',
  resetFlashcardProgressTitle: '重置记忆进度',
  resetFlashcardProgressDetail: '保留卡组、卡片和收藏，重新开始排程',
  confirmReset: '确认重置',
  reset: '重置',
  deleteAllFlashcardsTitle: '删除全部记忆卡',
  deleteAllFlashcardsDetail: '删除所有卡组和卡片',
  confirmDelete: '确认删除',
  delete: '删除',
  flashcardModuleConfirmNote: '此操作只影响记忆卡模块，请确认是否继续？',
  reminderHeading: '提醒',
  dailyReminderTitle: '每日复习提醒',
  dailyReminderDetail: '有到期卡片时按时提醒',
  notificationDenied: '通知权限被拒绝，请在系统设置中开启',
  on: '开启',
  off: '关闭',
  reminderTimeTitle: '提醒时间',
  nextReminderLabel: '下次提醒',
  reminderCountSuffix: (count) => ` · ${count} 张`,
  statusLabel: '状态',
  noReminderScheduled: '暂无待复习卡片，未安排提醒',
  practiceHeading: '练习',
  questionsLabel: '题目',
  practicedLabel: '已练习',
  starredLabel: '收藏',
  subjectsGroupTitle: '科目',
  subjectTotalSuffix: (total) => `${total}题`,
  subjectProgressSuffix: (count) => ` · ${count}条进度`,
  emptySubjectsNote: '暂无题库',
  resetPracticeProgressTitle: '重置练习进度',
  resetPracticeProgressDetail: '保留题库和收藏，只清空答题记录',
  deleteAllQuestionsTitle: '删除全部题库',
  deleteAllQuestionsDetail: '删除所有题目、进度和继续练习记录',
  subjectModuleConfirmNote: '此操作只影响该科目，请确认是否继续？',
  practiceModuleConfirmNote: '此操作只影响练习模块，请确认是否继续？',
  readingHeading: '阅读',
  collectionsLabel: '文集',
  documentsLabel: '文档',
  minutesLabel: '分钟',
  highlightsLabel: '高亮',
  bookmarksLabel: '书签',
  finishedLabel: '读完',
  resetReadingStatsTitle: '重置阅读统计',
  resetReadingStatsDetail: '保留文集、文档、高亮和书签',
  deleteAllReadingTitle: '删除全部阅读数据',
  deleteAllReadingDetail: '删除文集、文档、高亮、书签和阅读设置',
  readingModuleConfirmNote: '此操作只影响阅读模块，请确认是否继续？',
  backupHeading: '备份',
  fullBackup: '完整备份',
  exportFlashcardOnly: '仅导出记忆',
  exportQuizOnly: '仅导出练习',
  exportReadingOnly: '仅导出阅读',
  autoBackupGroupTitle: '自动备份',
  dailyAutoBackupTitle: '每日自动备份',
  dailyAutoBackupDetail: '自动保存完整备份到设备存储',
  lastBackupLabel: '上次备份',
  backupOk: '成功',
  backupFailed: '失败',
  locationLabel: '位置',
  backupNowTitle: '立即备份',
  backupNowDetail: '跳过 20 小时间隔，马上备份',
  backupNowAction: '备份',
  backupNowFailedToast: (error) => `备份失败: ${error}`,
  backupNowSuccessToast: '备份成功',
  restoreBackupTitle: '恢复备份',
  restoreBackupDetail: '从备份文件恢复数据',
  restoreBackupAction: '恢复',
  quarantineDetectedTitle: (count) => `检测到 ${count} 份受损数据`,
  quarantineDetail: '原始内容已保存为隔离副本，可先导出给外部工具修复，再通过恢复备份重新导入。',
  quarantineTimeUnknown: '时间未知',
  exportAction: '导出',
  discardAction: '丢弃',
  aboutHeading: '关于',
  intervalAlgorithmLabel: '间隔算法',
  displayFontLabel: '显示字体',
  displayFontValue: 'Source Serif · Noto Sans SC',
}
